// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_VSDsLtIUbrR8fRDpEeXM4oudol1iPG8',
    appId: '1:49471277644:web:9211c19be0b1d714cd42e9',
    messagingSenderId: '49471277644',
    projectId: 'carregou-meu-carro',
    authDomain: 'carregou-meu-carro.firebaseapp.com',
    storageBucket: 'carregou-meu-carro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUzdDPEZrIH1UX56cAc0TtgRUqHOWBF-Q',
    appId: '1:49471277644:android:1a5c6086e8ca839acd42e9',
    messagingSenderId: '49471277644',
    projectId: 'carregou-meu-carro',
    storageBucket: 'carregou-meu-carro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEXJngpc6ZWP3sJurDc6925acMYFfhLrc',
    appId: '1:49471277644:ios:81444174d11b16ffcd42e9',
    messagingSenderId: '49471277644',
    projectId: 'carregou-meu-carro',
    storageBucket: 'carregou-meu-carro.firebasestorage.app',
    iosClientId: '49471277644-gtoc3k5str8tpce48fucfee5053hmtt0.apps.googleusercontent.com',
    iosBundleId: 'com.salles.carregou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEXJngpc6ZWP3sJurDc6925acMYFfhLrc',
    appId: '1:49471277644:ios:81444174d11b16ffcd42e9',
    messagingSenderId: '49471277644',
    projectId: 'carregou-meu-carro',
    storageBucket: 'carregou-meu-carro.firebasestorage.app',
    iosClientId: '49471277644-gtoc3k5str8tpce48fucfee5053hmtt0.apps.googleusercontent.com',
    iosBundleId: 'com.salles.carregou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_VSDsLtIUbrR8fRDpEeXM4oudol1iPG8',
    appId: '1:49471277644:web:7fcabf376e9cd355cd42e9',
    messagingSenderId: '49471277644',
    projectId: 'carregou-meu-carro',
    authDomain: 'carregou-meu-carro.firebaseapp.com',
    storageBucket: 'carregou-meu-carro.firebasestorage.app',
  );

}